import { jsPDF } from "jspdf";

export function downloadReport(data) {
  const doc = new jsPDF();

  let y = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Function to add footer
  function addFooter() {
    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Resume Analyzer using Groq AI",
      20,
      pageHeight - 10
    );

    doc.text(
      `Page ${doc.getCurrentPageInfo().pageNumber}`,
      pageWidth - 30,
      pageHeight - 10
    );
  }

  // ================= HEADER =================

  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("AI Resume Analyzer", 20, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Professional ATS Analysis Report", 20, 27);

  y = 50;

  // ================= Resume Details =================

  doc.setTextColor(0);
  doc.setFontSize(12);

  doc.setFont("helvetica", "bold");
  doc.text("Resume Name:", 20, y);

  doc.setFont("helvetica", "normal");
  doc.text(data.fileName || "Unknown", 60, y);

  y += 10;

  const today = new Date();

  doc.setFont("helvetica", "bold");
  doc.text("Generated On:", 20, y);

  doc.setFont("helvetica", "normal");
  doc.text(
    today.toLocaleDateString() + " " + today.toLocaleTimeString(),
    60,
    y
  );

  y += 18;

  // ================= ATS Badge =================

  if (data.score >= 80) {
    doc.setFillColor(34, 197, 94);
  } else if (data.score >= 60) {
    doc.setFillColor(245, 158, 11);
  } else {
    doc.setFillColor(239, 68, 68);
  }

  doc.roundedRect(20, y - 6, 55, 12, 3, 3, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(`ATS: ${data.score}/100`, 26, y + 2);

  doc.setTextColor(0);

  y += 20;

  // ================= Section Function =================

  function addSection(title, content) {

    const lines = doc.splitTextToSize(content || "N/A", 165);

    const neededHeight = lines.length * 7 + 20;

    if (y + neededHeight > 270) {
      addFooter();
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(79, 70, 229);

    doc.roundedRect(15, y - 6, 180, 10, 2, 2, "F");

    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");

    doc.text(title, 20, y);

    y += 10;

    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");

    doc.text(lines, 20, y);

    y += lines.length * 7 + 10;
  }

  // ================= Sections =================

addSection("Resume Summary", data.summary);
addSection("Missing Skills", data.skills);

addSection("Strengths", data.strengths);

addSection("Weaknesses", data.weaknesses);

addSection("Suggestions", data.suggestions);

addSection("Interview Questions", data.interview);

addSection("Recommended Courses", data.courses);

// Footer on last page
addFooter();

  doc.save("AI_Resume_Report.pdf");
}